### PR TITLE
Make relative URLs in `e-` properties absolute

### LINKED ISSUE #181: Resolve relative URLs in e-* HTML content
Inspired by https://github.com/snarfed/bridgy-fed/issues/390#issuecomment-1408879534, open parsing issue https://github.com/microformats/microformats2-parsing/issues/38, related implementation details in https://github.com/microformats/mf2py/issues/138.

### PR DESCRIPTION
**Pull request by angelogladding**
Closes #181.

Does not support `srcset` -- should eventually reuse logic from https://github.com/microformats/mf2py/pull/188 when ready.

### CODE REVIEW

**Comment by capjamesg** [comment]
@angelogladding Is this PR ready for a review? If so, please mark me as a reviewer.

**Comment by angelogladding** [comment]
`srcset` can be added along with #188. Inclusion of the others listed in https://github.com/microformats/mf2py/issues/181#issuecomment-1625461973 can be debated and added at a later date.

**Review by capjamesg — APPROVED** [review]
Looks good!

**Comment by snarfed** [comment]
Really excited for this. Looks like it's ready to merge? I'd dearly love for it to go into 2.0!

**Pull request merged**
