### PR TITLE
Add block list for known conflicting root class names

### LINKED ISSUE #170: Ignore Tailwind's h- prefix values
Tailwind is a CSS framework that uses h- prefixed values for styling, specifically [height](https://tailwindcss.com/docs/height).

Therefore, the following example won't parse well in any correct implementation of microformats2.

```html
<html class="h-full">
...
<span class="h-card p-name">Johnny Appleseed</div>
...
</html>
```

The options for dealing with this seem to be:

1. make Tailwind go away permanently (honestly, I'm not a fan, but each to their own)
2. tell HTML authors to not use Tailwind with height properties if they're also using microformats2
3. ignore Tailwind's height properties (by default, ideally there should always be a way to get strict parsing) - the parsing spec apparently already excludes `h-[0-9]*` but we could also the other `h-` properties used by Tailwind

Given Tailwind doesn't seem to be going away, and given [priority of constituencies](https://www.w3.org/TR/html-design-principles/#priority-of-constituencies) ("consider users over authors over implementors over specifiers over theoretical purity"), the third option may be the least bad, even if it does make parsing marginally more complicated.

### PR DESCRIPTION
**Pull request by angelogladding**
Closes #170.

I'm seeing `h-px, h-auto, h-full, h-screen, h-min, h-max, h-fit` in the Tailwind docs. None of these seem to be good candidates for root class names so there shouldn't be an issue of vocabulary gatekeeping.

The general feeling I get from https://github.com/microformats/microformats2-parsing/issues/59 is that parser experimentation would be a good path forward. This change can easily be reverted at a later date.

In the meantime we have a fix for the current landscape and a framework for solving similar issues moving forward.

### CODE REVIEW

**Comment by sknebel** [comment]
This should be behind a flag IMHO.

**Comment by angelogladding** [comment]
Or should there be a flag to turn it off? It'll do only good right now and if someone somewhere wants to experiment with e.g. `h-screen` they can use the flag. Consumers of their `h-screen` will have to explicitly use the flag as well but their consumption of a new microformat would probably already need other manual steps to support.

**Comment by sknebel** [comment]
I strongly believe default behavior of microformats parsers should be as similar as possible. Parser bugs already regularly cause confusion when someone checks their pages with one parser and then is confused why an application using a different parser does not understand it correctly.

**Comment by gRegorLove** [comment]
Agreed, I think it should be behind a flag and (probably) configurable, like an option to initialize the parser with a custom list of class names to block.

This would allow a specialized app like indiewebify.me to choose to ignore any conflicting classes that arise over time, without requiring an update to the list of static class names in the parser.

**Comment by angelogladding** [comment]
@sknebel @gRegorLove what's a good flag? leave the tailwind-specific classes out of the library entirely and just let the user bring their own block list?

    >>> parser(url="example.com", block_roots={
    ...     "h-px", "h-auto", "h-full", "h-screen", "h-min", "h-max", "h-fit"
    ... })

**Comment by gRegorLove** [comment]
If it's behind a flag I don't have a strong opinion about including Tailwind classes in the package. If you do, maybe it could have three states:

- default (no blocked classes)
- block roots enabled (packaged list of classes is blocked)
- block roots enabled + custom list of classes provided (only the custom list of classes is blocked)

**Comment by sknebel** [comment]
One way might be to have the list be user-provided, but have a ready-to-use list as a constant available. `filter_roots=mf2py.ROOT_FILTER_PRESET_TAILWIND` ?

**Comment by angelogladding** [comment]
It's tempting to try to leverage this function https://github.com/microformats/mf2py/blob/main/mf2py/mf2_classes.py#L9 but it wasn't the right place to reject items.

As implemented, this method will only work on root (h-) classes. This works for the current Tailwind use case but won't extend to future elemental (u-, dt-, p-, e-) conflicts.

**Review by tantek — APPROVED** [review]
This seems worth experimenting with a flag as commenters have said. LGTM.

**Pull request merged**
