### PR TITLE
Add extension to support metaformats

### PR DESCRIPTION
**Pull request by snarfed**
implements all of https://microformats.org/wiki/metaformats except explicit microformats2 classes on `<meta>` tags. also falls back to inferring `name` from `<title>` and `summary` from `meta[name=description]`, neither of which is (yet) part of the official metaformats spec.

### CODE REVIEW

**Comment by sknebel** [comment]
I think it wold make sense for metaformats to be an external extension at this point, since I kind of expect that people would want/need to experiment with variations of it instead of relying on it being updated with mf2py.

But as long as it's behind a flag I'm also not strictly against including it.

**Comment by snarfed** [comment]
Looks like we have a +0 or +1 on this from @angelogladding, a -0 from @sknebel (I think), and a +0 from me. @capjamesg any opinion on whether we merge or reject this PR?

**Comment by capjamesg** [comment]
I agree with @sknebel's note above.

**Comment by snarfed** [comment]
OK! Sounds good. Feel free to go ahead with 2.0!

**Comment by snarfed** [comment]
I'm ok either way! Up to you all.

**Comment by capjamesg** [comment]
Reading over this again, @sknebel's suggestion wasn't explicitly for an extensions API. @sknebel, thank you for encouraging me to revisit this. My comment from yesterday was conflation on my part from another related discussion Angelo and I were having re: how we structure additional functionality that is not explicitly microformats, as well as what we think about as an "extension" right now (image alt text being the only implementation at present).

I understand there are situations where someone would only want a metaformats parser. The integration in the microformats parser feels right given that metaformats are in discussion by the microformats community. Given the work already done by @snarfed, and its elegant -- and non-intrusive -- usage of the current `Parser` class, it felt prudent to accept this PR as is.

**Comment by angelogladding** [comment]
I believe developers that want the `<META>` items in mf2json format also want the mf2s on the same page. Those who don't can obviously ignore the normal mf2 items. This works trivially if we stuff a top level `meta-item` property (vs a `source=metaformats` property on the last item of `items`) -- see https://github.com/microformats/metaformats/issues/2 and idea no. 3 in https://github.com/microformats/mf2py/issues/197#issuecomment-1811675685 with which I agree.

I believe the functionality should wind up here eventually so I'd rather skip the overhead of a second project if possible. @sknebel do you foresee there being too many changes up front or all throughout the lifetime of the metaformats spec?

We've already committed to release more frequently. Remember, the road to mf2py 2.0 started with a call to "modernize". It has included deprecating py2, improving the project tooling, cleaning up old issues *and* implementing modern mf2 features. 2.1 will be more focused and lightweight. And we shouldn't hesitate to shoot to 3.0 from there if we need (as I believe we've already discussed). In that case this project should be well suited to absorb the initial high rate of change that metaformats inclusion may bring.

From a branding perspective mf2py can rebrand from "MicroFormats2 for PYthon" to "[Micro|Meta]Formats 2 PYthon" without telling anyone.

**Pull request merged**
