### PR TITLE
Prepare release for 1.1.3

### PR DESCRIPTION
**Pull request by angelogladding**
Release five fixes/features along with a setup.py `python_requires` version specifier in anticipation of python2 deprecation. See https://github.com/microformats/mf2py/issues/87#issuecomment-1610297218

### CODE REVIEW

**Comment by angelogladding** [comment]
Needs the date in the CHANGELOG to be updated on date of publish.

**Review by tantek — APPROVED** [review]
docs look good to me. still would be good for @kevinmarks to double-check.

**Comment by sknebel** [comment]
LGTM. I'm confident enough in these changes to release them without tests working right now (since they were tested at the time), which allows us to fix CI afterwards, for 3.x only

**Comment by sknebel** [comment]
I look into publishing the release on the weekend - I should have the necessary setup and permissions, but it's been a while....

**Comment by capjamesg** [comment]
@sknebel Can you give me `Maintainer` permissions on PyPi for `mf2py`? I am `capjamesg` on PyPi.

**Comment by capjamesg** [comment]
When we do the PyPi release, we should create a new Release on GitHub, too.

**Pull request merged**
